### PR TITLE
bump tpm2-tss to 1.2.0 for pyro

### PR DESCRIPTION
**Pull request by cardoe**
The tools were bumped but not the library itself

### CODE REVIEW

**Comment by cardoe** [comment]
This is what the security flags tweak fixes
```
| poky-linux/tpm2.0-tss/1.1.0-r0/recipe-sysroot-native/usr/bin/x86_64-poky-linux/../../libexec/x86_64-poky-linux/gcc/x86_64-poky-linux/6.3.0/ld: /var/build/build/tmp/work/corei7-64-poky-linux/tpm2.0-tss/1.1.0-r0/recipe-sysroot/usr/lib/libc_nonshared.a(elf-init.oS): relocation R_X86_64_PC32 against undefined hidden symbol `__init_array_start' can not be used when making a shared object
| /var/build/build/tmp/work/corei7-64-poky-linux/tpm2.0-tss/1.1.0-r0/recipe-sysroot-native/usr/bin/x86_64-poky-linux/../../libexec/x86_64-poky-linux/gcc/x86_64-poky-linux/6.3.0/ld:
final link failed: Bad value
| collect2: error: ld returned 1 exit status
```

**Comment by cardoe** [comment]
So honestly my fix isn't the "right" thing because the right thing would be to fix the code so that it compiles properly. But I figured since these are released versions you wouldn't want to necessary carry a patch. I only briefly looked at it and it took me into a pile of macros and I decided that 1 cup of coffee wasn't enough to fight macros.

**Comment by cardoe** [comment]
This was the actual error behind #45 as well.

**Comment by flihp** [comment]
Thanks for the data on this @cardoe. Giving this a build tonight. Will see about the "right" solution. I don't mind carrying a patch so long as it goes upstream too.

**Pull request merged**
