### PR TITLE
Tpm2 git

### PR DESCRIPTION
**Pull request by pietrushnic**
We trying to use `tpm2-tools` master and made some modifications to `meta-measured`. This PR has the following problem:

```
root@genericx86-64:~# tpm2_pcrlist

** (process:553): CRITICAL **: 22:08:31.195: failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: GDBus.Error:org.freedesktop.DBus.Error.Spawn.FileInvalid: Cannot do system-bus activation with no user

ERROR: tcti init allocation routine failed for library: "tabrmd" options: "(null)"
ERROR: Could not load tcti, got: "tabrmd"
```

Any idea what we doing wrong?

### CODE REVIEW

**Comment by pietrushnic** [comment]
@macpijan FYI

**Comment by flihp** [comment]
Thanks for the patches. I've been trying to find the time to upgrade these recipes for a while now. Will get this tested over the weekend.

**Comment by flihp** [comment]
I just fought through the RRECOMMENDS patch trying to get the master branch building. Will be cherry picking the required patches from your branch to accomplish this since it looks like you've got everything here.

**Comment by flihp** [comment]
Apologies for the delay. It's been ~6 months since I've touched OE and the combination of me forgetting how this stuff works and upstream changes has required some work on my end to set up a build / test environment. Also since your first comment here indicates you're having trouble using the various tpm2 bits on whatever platform you're using I'm expecting we'll need to have some sort of common testing environment.

In the past I've used the minnowboard for testing but that platform is getting pretty old and no everyone has one. So as part of integrating this I've done two things
1) set up a 'sumo' branch since this is the latest stable release
2)  create a qemu machine for both tpm 1.2 and 2.0 testing

The QEMU tpm support requires the libtpms / swtpm work that can be found here:
- https://github.com/stefanberger/libtpms
- https://github.com/stefanberger/swtpm

The QEMU shipped with OE supports the TPM stuff so the only work required to run images built using the qemux86-64-tpm and qemux86-64-tpm2 MACHINEs is to run the swtpm daemon with the right options to get tpm 1.2 or 2.0, and to execute the runqemu command with the right options to connect it to the swtpm daemon.

As part of doing this I've cherry-picked 341f4a2 and 1a95436 from this PR. All of this has been merged back into the master This will mean a rebase for you all, apologies for that. On master I'm seeing a build error for the 1.2 tpm-tools but in the interest of making progress I've pushed all this regardless and will work to fix that up soon.

The logical next steps are to rebase this PR on master and see if you're able to build and run the tpm2 stuff with the qemux86-64-tpm2 + swtpm. The PR should hopefully be only the recipe updates after this. I'll start looking at those in parallel.

Thanks again for all the work you've put into this!

**Comment by flihp** [comment]
PR now has conflicts given fixes made to master. Please rebase and force push to the same branch as this PR to keep from splitting this discussion across multiple PRs if possible.

**Comment by flihp** [comment]
scripts that may make experimentation with swtpm / runqemu + tpm easier are here: https://github.com/flihp/oe-build-scripts/tree/master/bin

**Comment by macpijan** [comment]
Already rebased to master and built successfully. I hope to test that tomorrow in qemu.
I also removed the libs from packagegroup (f0f525c), as I have already packaged them into single `libtss2` package. In the current form, `libtss2-esys/mu/sys/tcti-*` seemed to me to belong to a single package. Let me know if we should split it somehow into smaller parts.

**Comment by flihp** [comment]
Thanks for the quick turn-around on this. Building & testing now

Picking apart the separation of modules / packages in this PR feels like bikeshedding. My goal is to decompose these things as far as is practical so that users only get the libs they're using. I can go back and waste time on that after your recipe upgrade gets merged.

**Comment by flihp** [comment]
I've got this tested on qemu for 1.2 and 2.0. This did require minor fixups but for the sake of time I'm going to merge this PR as-is and do the fixups manually.

**Pull request merged**
